name: Test Update Contributions

on:
  schedule:
    - cron: '1 0 * * 1'
  workflow_dispatch:

jobs:
  test-update-contributions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache Node.js modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-18-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-18-
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Cache PRs
        id: cache-prs
        uses: actions/cache@v4
        with:
          path: test-data/pr-cache.json
          key: test-pr-cache

      - name: Cache all contributions data
        id: cache-all-data
        uses: actions/cache@v4
        with:
          path: test-data/all-contributions.json
          key: test-contributions-data

      - name: Run contribution script
        id: run-script
        run: node test-update-contributions.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
          SINCE_YEAR: ${{ secrets.SINCE_YEAR }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
          git add test-contributions/ test-data/
      
          git diff --staged --quiet || (git commit -m "docs: Update contributions [skip ci]" && git push)
